apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python-crud-adas
  labels:
    app: api-python-crud-adas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-python-crud-adas
  template:
    metadata:
      labels:
        app: api-python-crud-adas
    spec:
      containers:
        - name: api-python-crud-adas
          image: ericarocha/python-crud-adas
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000